version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "tuesday"
    labels:
      - "dependencies"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
